# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Learning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetwork', '~> 0.1.0'
pod 'RxSwift', '~> 4.4.0'
pod 'RxCocoa', '~> 4.4.0'
pod 'ReactiveCocoa', '~> 2.0'
pod 'Curry', '~> 4.0.0'

  # Pods for Learning

  target 'LearningTests' do
    inherit! :search_paths
    # Pods for testing
    	pod 'RxBlocking', '~> 4.4.0'
	pod 'RxTest', '~> 4.4.0'

  end

  target 'LearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
